<?php 

namespace Cradle\Storm;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:02.
 */
class Cradle_Storm_PostGreSql_Test extends TestCase
{
    /**
     * @var PostGreSql
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = SqlFactory::load(include(__DIR__.'/assets/pgsql.php'));
		$schema = file_get_contents(__DIR__.'/assets/pgsql-schema.sql');
		$this->object->query($schema);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Cradle\Storm\PostGreSql::connect
     */
    public function testConnect()
    {
		$instance = $this->object->connect(include(__DIR__.'/assets/pgsql.php'));
		$this->assertInstanceOf('Cradle\Storm\PostGreSql', $instance);
    }

    /**
     * @covers Cradle\Storm\PostGreSql::getAlterQuery
     */
    public function testGetAlterQuery()
    {
		$instance = $this->object->getAlterQuery('foobar');
		$this->assertInstanceOf('Cradle\Storm\PostGreSql\QueryAlter', $instance);
    }

    /**
     * @covers Cradle\Storm\PostGreSql::getColumns
     */
    public function testGetColumns()
    {
		$actual = $this->object->getColumns('address');
		$this->assertTrue(is_array($actual));
    }

    /**
     * @covers Cradle\Storm\PostGreSql::getCreateQuery
     */
    public function testGetCreateQuery()
    {
		$instance = $this->object->getCreateQuery('foobar');
		$this->assertInstanceOf('Cradle\Storm\PostGreSql\QueryCreate', $instance);
    }

    /**
     * @covers Cradle\Storm\PostGreSql::getDeleteQuery
     */
    public function testGetDeleteQuery()
    {
		$instance = $this->object->getDeleteQuery('foobar');
		$this->assertInstanceOf('Cradle\Storm\PostGreSql\QueryDelete', $instance);
    }

    /**
     * @covers Cradle\Storm\PostGreSql::getIndexes
     */
    public function testGetIndexes()
    {
		$actual = $this->object->getIndexes('address');
		$this->assertTrue(is_array($actual));
    }

    /**
     * @covers Cradle\Storm\PostGreSql::getInsertQuery
     */
    public function testGetInsertQuery()
    {
		$instance = $this->object->getInsertQuery('foobar');
		$this->assertInstanceOf('Cradle\Storm\PostGreSql\QueryInsert', $instance);
    }

    /**
     * @covers Cradle\Storm\PostGreSql::getPrimary
     */
    public function testGetPrimary()
    {
		$actual = $this->object->getPrimary('address');
		$this->assertTrue(is_array($actual));
    }

    /**
     * @covers Cradle\Storm\PostGreSql::getSelectQuery
     */
    public function testGetSelectQuery()
    {
		$instance = $this->object->getSelectQuery('foobar');
		$this->assertInstanceOf('Cradle\Storm\PostGreSql\QuerySelect', $instance);
    }

    /**
     * @covers Cradle\Storm\PostGreSql::getTables
     */
    public function testGetTables()
    {
        $actual = $this->object->getTables();
		$this->assertEquals('address', $actual[0]['tablename']);
    }

    /**
     * @covers Cradle\Storm\PostGreSql::getUpdateQuery
     */
    public function testGetUpdateQuery()
    {
		$instance = $this->object->getUpdateQuery('foobar');
		$this->assertInstanceOf('Cradle\Storm\PostGreSql\QueryUpdate', $instance);
    }

    /**
     * @covers Cradle\Storm\PostGreSql::setSchema
     */
    public function testSetSchema()
    {
		$instance = $this->object->setSchema('public');
		$this->assertInstanceOf('Cradle\Storm\PostGreSql', $instance);
    }

    /**
     * @covers Cradle\Storm\PostGreSql::getUtilityQuery
     */
    public function testGetUtilityQuery()
    {
		$instance = $this->object->getUtilityQuery();
		$this->assertInstanceOf('Cradle\Storm\PostGreSql\QueryUtility', $instance);
    }
}
