<?php

namespace Cradle\Storm\Query;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:02.
 */
class Cradle_Storm_Query_AbstractQuery_Test extends TestCase
{
  /**
   * @var AbstractQuery
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new AbstractQueryStub;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @covers Cradle\Storm\AbstractQuery::__toString
   */
  public function test__toString()
  {
    $this->assertEquals('foobar', $this->object->__toString());
  }
}

if(!class_exists('Cradle\Storm\AbstractQueryStub')) {
  class AbstractQueryStub extends AbstractQuery
  {
    public function getQuery(): string
    {
      return 'foobar';
    }
  }
}
