<?php

namespace Cradle\Storm\Query\MySql;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:03.
 */
class Cradle_Storm_Query_MySql_Utility_Test extends TestCase
{
  /**
   * @var QueryUtility
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Utility;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }

  /**
   * @covers Cradle\Storm\Query\MySql\Utility::dropTable
   */
  public function testDropTable()
  {
    $instance = $this->object->dropTable('foobar');
		$this->assertInstanceOf('Cradle\Storm\Query\MySql\Utility', $instance);
  }

  /**
   * @covers Cradle\Storm\Query\MySql\Utility::getQuery
   */
  public function testGetQuery()
  {
    $actual = $this->object->getQuery();
		$this->assertEquals(';', $actual);
  }

  /**
   * @covers Cradle\Storm\Query\MySql\Utility::renameTable
   */
  public function testRenameTable()
  {
    $instance = $this->object->renameTable('foo', 'bar');
		$this->assertInstanceOf('Cradle\Storm\Query\MySql\Utility', $instance);
  }

  /**
   * @covers Cradle\Storm\Query\MySql\Utility::showColumns
   */
  public function testShowColumns()
  {
    $instance = $this->object->showColumns('foobar');
		$this->assertInstanceOf('Cradle\Storm\Query\MySql\Utility', $instance);
  }

  /**
   * @covers Cradle\Storm\Query\MySql\Utility::showTables
   */
  public function testShowTables()
  {
    $instance = $this->object->showTables('foobar');
		$this->assertInstanceOf('Cradle\Storm\Query\MySql\Utility', $instance);
  }

  /**
   * @covers Cradle\Storm\Query\MySql\Utility::truncate
   */
  public function testTruncate()
  {
    $instance = $this->object->truncate('foobar');
		$this->assertInstanceOf('Cradle\Storm\Query\MySql\Utility', $instance);
  }
}
